FOS\UserBundle\Model\User:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups : [user]
        username:
            expose: true
            groups : [user]
        email:
            expose: true
            groups : [user]