<?php
/**
 * Created by PhpStorm.
 * User: zaytsev
 * Date: 11.07.16
 * Time: 10:32
 */

namespace Blogger\BlogBundle\Entity\Repository;


/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    


}